// flow-typed signature: bb27aa0ed14d1e118ca352d4a01c6376
// flow-typed version: <<STUB>>/ethers_v5.x.x/flow_v0.135.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ethers'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ethers' {
  declare class Signer {
    getAddress(): Promise<string>
  }
  
  declare class Web3Provider {
    constructor(provider: any): void;
    
    getSigner(): Signer;
  }
  
  
  declare module.exports: {
    providers: {
      Web3Provider: typeof Web3Provider,
    }
  };
}
